### ISSUE TITLE
Character gets flung when limb gets decapitated

### ISSUE THREAD

**Issue by TheTrueRedFrogy** [MemeFrug/Vandalism#2]
when you jump and a limb is cut off you get **sent flying off the map** at **incredible speeds**

How to do the bug:
1. get your limb cut off by a sword or the hit brick
2. jump

Fix:   (maybe)
1. cut off limb
2. when cut clone the limb and delete the original
3. have it disappear after sometime so it doesnt hang around on the floor forever

**Comment by MemeFrug** [comment]
Please say how to reproduce it (the steps on how I would replicate tlit on my end) not how to fix it 😁 that's my job haha

**Comment by MemeFrug** [comment]
Thanks for updating!
