### ISSUE TITLE
Blood Squirts/Improvements

### ISSUE THREAD

**Issue by TheTrueRedFrogy** [MemeFrug/Vandalism#6]
**Description:**
Blood lands on the player and floats there when you move away
Blood stays inside the torso of the dummy (most likely fix would be to move it to the part of dismemberment)

**Steps to reproduce the behavior:**
1. Cut dummies arm
2. Be disappointed

**What's expected:**
Blood hits the floor no floating no torso blood inside action

**Screenshots:**
![image](https://user-images.githubusercontent.com/68794100/147640028-bbf90bfb-034e-4e5c-a541-10061403af3d.png)
![image](https://user-images.githubusercontent.com/68794100/147640116-7afa9c5c-eb65-4f66-893d-a5180673f8dc.png)

**Comment by MemeFrug** [comment]
Fixed The Morphing of blood and blood floating and Blood now spawns on the dummys cut arm for awhile and spawn on the dead dummy, im not making in anymore realistic for obvious reasons. Game starts to lag with the blood so, prob need to fix by removing alot of bug.

Thanks!
